stormpath/express-stormpath

.npmignore

The .npmignore will remove the documentation, tests, and other unnecessary code for production use. This cuts out roughly 20MB of files that aren't necessary to run in production, and it only affects the publish to the npm registry, not the entire project.

Remove the unnecessary files from the node module.

---

lib/helpers.js

app.use(stormpath.init(app, {
...
renderHandler: function(view,res,options) {
// custom render handling here - use jade, handlebars etc or just set some extra form options
},
...
}
adding this option allows the developer to use their own view engine (jade / handlebars etc) when rendering any of the stormpath views. It also allows the developer to add / remove options before the view is rendered

allow user to specify custom render handler

---

lib/settings.js
lib/stormpath.js

We found ourselves wanting to use a pre-configured Redis connection, specifically for the authentication support.  I believe the solution will work for a pre-configured Memcached client, too.
I reached the application limit when running the full suite of tests.  If you have a workaround, I am happy to run the tests locally to verify this changeset.

Adds support for passing in a caching client directly

---

lib/stormpath.js

We shouldn't validate until after the underlying Node SDK has run, as it populates any values from the environment and subsequent resource calls to the API

Fixing order of config validation

---

docs/changelog.rst
docs/upgrading.rst
lib/controllers/forgot-password.js
lib/stormpath.js
test/controllers/test-forgot-password.js

This endpoint was expecting a `username` property, but this is not correct.  It should be `email`.  The Stormpath API only accepts email for password reset.

Fixing /forgot JSON api, expects email

---

docs/changelog.rst
docs/upgrading.rst
lib/controllers/login.js
lib/controllers/register.js
lib/helpers/login-responder.js
lib/stormpath.js
test/controllers/test-register.js
test/handlers/test-me.js
test/handlers/test-post-login-handler.js
test/handlers/test-post-registration-handler.js

* Fixing the `postRegistrationHandler`, it is now called even if `config.web.register.autoLogin` is `false`.  It now receives an expanded account object.
* Fixing the `postLoginHandler`, it now receives an expanded account object.
* Writing test to assert the `/me` route is expanding the custom data
Closes #114 #124 #123

Fixing post-login and post-registration handlers

---

test/controllers/test-register.js
test/handlers/test-me.js
test/handlers/test-post-login-handler.js
test/handlers/test-post-registration-handler.js
test/helpers.js
test/test-stormpath.js

Most of these were my fault, oopsies :)
I also added the package name and a per-process uuid to the application name, so that (a) I could see how many apps were being leftover per run and (b) so that others can know that this is our library

Fix tests that aren’t cleaning up application resources

---

lib/controllers/google-login.js
lib/controllers/linkedin-login.js

handlers are retrieved from the application, but there is no trace of them being ever set Let's get them from the config.

post*Handlers are not invoked for google (and likely for linkedin)

---

lib/middleware/api-authentication-required.js

Originally from #148, but inability to get Travis to work with building that (probably because it's a PR from fork) I created this instead.
Closes #148, #138.

Make api-authentication-required expose the authenticationResult into the request/response

---

lib/controllers/facebook-login.js

We want to send the error message directly to the browser, we don’t have a specific error view for this case (that was from the 1.x version)

Fix rendering of errors during Facebook login attempt

---

lib/helpers/create-session.js

The reference to `https` was undefined, which meant that we would pass undefined for the secure value (which meant that the secure value was never set to true).  This PR fixes that.

Fix: secure cookie properties

---

lib/helpers/get-required-registration-fields.js
lib/helpers/validate-account.js
test/controllers/test-register.js

This is more user-friendly than "givenName", etc.
To verify:
Use our [sample project](https://github.com/stormpath/express-stormpath-sample-project) and visit the registration form.  Use your web inspector to remove the `required` attribute from the "First Name" field, so that HTML form validation does not prevent you from submitting the form.  Submit the form and you should see the error "First Name required"
This should go in a minor release, and the upgrade log should note that the error messages are changing (as some may be depending on the errors, particularly if using the JSON responses)

Use field label when rendering field validation errors

---

lib/client.js

Fix issue with `EnrichIntegrationFromRemoteConfigStrategy` being run before `EnrichIntegrationConfigStrategy `. This resulted in `EnrichIntegrationFromRemoteConfigStrategy` not being able to pick up some flags that were being set by `EnrichIntegrationConfigStrategy` at runtime.

Fix: Change config load order

---

docs/upgrading.rst

Adds some info about changed routes when upgrading from v1.x to v2.x.
Fixes #243

Fix: Add info about changed routes in upgrade docs from v1 to v2

---

lib/stormpath.js

Small internal refactor. Simply make the use of `serveAngular()` clearer by renaming it to `addSpaRoute()`.

Refactor: Rename serveAngular as addSpaRoute

---

lib/helpers/body-parser.js
lib/helpers/index.js
lib/stormpath.js
package.json
test/helpers/test-body-parser.js

Removes the `body-parser` dependency and instead uses the `body` and `qs` module to parse JSON and query string encoded request bodies.
Fixes #194 and #180

Fix: Remove body-parser dependency

---

lib/helpers/get-app-module-version.js
lib/helpers/index.js
lib/stormpath.js

Currently the Express version that we report in our user agent is the one that we have loaded in our package (`express-stormpath`). I.e. it might not be the same that the user is actually using.
Therefore I suggest this fix, so that we resolve the package ourselves by first looking in the path of the running process and its node_modules directory, then if that doesn't exist we fall back to the global node_modules directory.
If we are able to find a module in either one of those directories, then we simply load the package.json file from there and get the version.
Fixes #239

Fix: Load express version from application modules

---

lib/helpers/body-parser.js
lib/stormpath.js

Fixes the default body parser object issue (#264) by only forcing a default body on requests that we serve and fixes the body parser hang issue (#276) by only parsing the body when it hasn't already been parsed.
1. Checkout this branch (`fix-body-parser-middleware`).
2. Execute `$ npm link` so that we can link to it.
3. Create a new directory and configure a new Node.js server according to [this gist](https://gist.github.com/typerandom/11d2d428e5565ef7a57d).
4. Execute `$ npm link stormpath-express` so that we're linking to our `fix-body-parser-middleware` branch.
5. Start the server.
6. Navigate to [http://localhost:3000/register](http://localhost:3000/register).
7. Create a new account.
8. Navigate to [http://localhost:3000/forgot](http://localhost:3000/forgot).
9. Request a new …

Fix: Body parser middleware issues

---

lib/controllers/facebook-login.js
lib/controllers/google-login.js
lib/controllers/linkedin-login.js
lib/helpers/login-with-oauth-provider.js
lib/oauth/error-responder.js
lib/oauth/index.js
lib/views/facebook_login_form.jade
lib/views/linkedin_login_form.jade

Fixes #288.
Errors during social login is today displayed as json (see #288). This PR fixes so that the error is instead displayed as an error on the login form. It also shows a more specific error message when email was not provided.
**Please see *Discussion* before reviewing.**
After I've made this, I found out that there are views for displaying social login errors (e.g. `facebook_login_failed.jade`), but they doesn't seem to be used.
However, I found it better to display the error on the login form as it allows the user to try again.
Question is, what solution should I go with? Implementing the error views or use the login form as this PR does? If the latter, I should probably show the registration form instead if the error occurred during signup, which is not possible to know at the …

Make sure that OAuth callback errors gets handled

---

lib/controllers/github-login.js
lib/controllers/index.js
lib/oauth/common.js
lib/views/base.jade
lib/views/github_login_form.jade
lib/views/login.jade

Fixes #312.
This PR implements support for GitHub [social login](https://github.com/stormpath/stormpath-framework-spec/blob/master/social.md#feature-description).
This implementation is more or less just a copy of the Google and LinkedIn implementations. I decided to not do any refactors as it will be easier to do them all together later.
I also used `exchangeAuthCodeForAccessToken()` from the LinkedIn implementation and placed it in `oauth/common.js` with some minor changes. I've not refactored LinkedIn to use this new method as that would create more review work.
* This PR is going to be merged into `framework-spec-upgrade`.
* If at least four providers are configured, they will take up too much visual space (see the screenshot). One suggestion to fix this could be to vertically center …

Implement support for GitHub social login

---

lib/config.yml
lib/controllers/login.js
lib/helpers/get-login-view-model.js
lib/helpers/index.js
test/helpers/test-get-login-view-model.js

Fixes #306.
This PR implements a JSON view model for `GET` on `/login` according to the [spec](https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#login-view-model).
* This PR is going to be merged into `framework-spec-upgrade`.
* I'm not sure if the account stores should only include SAML and social providers, or just all of them. If so, how do I filter them out?
* Added some unit tests (all methods are not tested):
```bash
helpers/get-login-view-model.js
getFormFields(config)
✓ should return a non-empty array
✓ should only return fields with `enabled` set to `true`
✓ should remove the `enabled` property from returned fields
✓ should return the fields in order of `config.web.login.fieldOrder`
getAccountStoreModel(accountStore)
✓ should return an object
return …
```

JSON view model for GET on /login

---

lib/config.yml
lib/controllers/login.js
lib/controllers/verify-email.js
lib/helpers/handle-accept-request.js

Adds support for the web.spa option.
This depends on #313 to be merged before being reviewed.
What should the default `web.spa.view` value be? I've just set it to `index`, since that is [what the framework spec states](https://github.com/stormpath/stormpath-framework-spec/blob/master/web-config.yaml#L214). But doesn't really make any sense since there won't be any file named `index`.
One solution that I think makes sense would be to set it to `null`, then have a validation step when the configuration is being loaded, to assert that if `web.spa.enabled` is set to `true`, then a value for `web.spa.view` must also be provided.
2. Run `$ npm link`.
3. Checkout the [React example app](https://github.com/stormpath/stormpath-express-react-example).
4. Run `$ npm link …

Add web.spa option support

---

lib/controllers/register.js

Implements the produces option for /register according to [the framework spec](https://github.com/stormpath/stormpath-framework-spec/blob/master/registration.md#feature-description).
2. Clone [express-stormpath-sample-project](https://github.com/stormpath/express-stormpath-sample-project).
3. Use `npm link` and `npm link express-stormpath` to link the library to the example project.
4. Start the server.
5. Navigate to `http://localhost:3000/register`.
6. Sign up for a new account.
7. Open up the terminal and execute `$ http POST localhost:3000/register givenName=test surname=tester email=[your name]+123@stormpath.com password=Test12345_ --json`.
8. Verify that you get a `200 OK` response with the account data as a JSON body.
9. Modify your configuration and change …

Add produces option for /register

---

lib/controllers/change-password.js
lib/controllers/forgot-password.js
test/controllers/test-reset-password.js
test/fixtures/spa-root-fixture.js

Implements the produces option for `/forgot` according to the framework spec.
2. Clone [express-stormpath-sample-project](https://github.com/stormpath/express-stormpath-sample-project).
3. Use `npm link` and `npm link express-stormpath` to link the library to the example project.
4. Start the server.
5. Navigate to `http://localhost:3000/forgot`.
6. Submit your email.
7. Open up the terminal and execute `$ http POST localhost:3000/forgot email=[your name]@stormpath.com --json`.
8. Verify that you get a `200 OK` response.
9. Modify your configuration and change `web.produces` to `['text/html', '']` (hack because extender currently merges arrays... which needs to be fixed, empty string overwrites second array item.).
10. Verify that step 5-6 works, but that step 7 …

Add produces option for /forgot

---

README.md
docs/configuration.rst
lib/controllers/login.js
lib/controllers/verify-email.js
lib/helpers/handle-accept-request.js
lib/helpers/spa-handler.js
lib/helpers/spa-response-handler.js
lib/stormpath.js
package.json
test/fixtures/produces-fixture.js
test/produces.js

**Description of changes:**
* Determine the correct content type response, based on accept header preferences and produces configuration
* New test suite to assert that the correct content type is being served, given the supplied `stormpath.web.produces` configuration.
* Consolidate SPA serving into a single place.
**Verification**
Run the new tests :) Or checkout the the [express-stormpath-sample-project](https://github.com/stormpath/express-stormpath-sample-project) and modify the `web.produces` configuration with various options, and assert that you get the correct content types when you change the Accept header for your requests.
**Meta/Discuss**
I'm happy with the new test suite, but not so happy with what's going on inside `handleAcceptRequest`.  Dealing with the SPA serving inside …

Changes to support the produces option

---

lib/stormpath.js
package.json

Adds support for the `X-Stormpath-Agent` header.
This depends on https://github.com/stormpath/stormpath-sdk-node/pull/393. So that PR needs to be merged/released and used by this PR before this will function as expected.
This solution is a bit of a hack. The issue is that we set the `userAgent` when we create our `Node SDK` client. An instance that is only created once and shared among all requests `app.get('stormpathConfig')`. So when we change the `userAgent` config in runtime, it will affect all requests making client API calls. I.e. if the user would host one API and run both Angular and React (which both would send their own `X-Stormpath-Agent` headers, then there's a chance that the requests would overlap and the `User-Agent` header sent would be inconsistent with the request.
* …

Add support for the X-Stormpath-Agent header

---

docs/authentication.rst
lib/config.yml

This PR changes the default configuration to use [local token validation](http://docs.stormpath.com/nodejs/express/latest/authentication.html#token-validation-strategy). It also updates the documentation accordingly.
You can always test that the token validation is actually local, but since there are no code changes is this PR, a review of the configuration and documentation changes would be sufficient.
Fixes #315.

Use local token validation by default

---

docs/logout.rst
lib/stormpath.js
test/controllers/test-logout.js

Changes the `/logout` endpoint to only respond to POST requests.
2. Link it (`$ npm link`).
3. Create a new test application using [this gist](https://gist.github.com/typerandom/587ea241ec04eb2152af).
4. Link to our branch (`$ npm link express-stormpath`).
5. Start the application.
6. Navigate to `/logout`.
7. Verify that you get a `HTTP 404` response.
8. Navigate to `/login`.
9. Login as an existing user.
10. You should now be seeing a `Logout` button.
11. Press the `Logout` button and verify that you're no longer logged in.
Fixes #352.

Change logout endpoint to only respond to POST requests

---

README.md
docs/configuration.rst
docs/login.rst
docs/logout.rst
docs/registration.rst
docs/upgrading.rst
lib/client.js
lib/config.yml
lib/controllers/register.js
lib/helpers/get-form-model.js
lib/helpers/get-form-view-model.js
lib/helpers/get-required-registration-fields.js
lib/helpers/prep-account-data.js
lib/helpers/sanitize-form-data.js
lib/helpers/validate-account.js
lib/views/login.jade
test/controllers/test-register.js
test/controllers/test-social-providers.js
test/fixtures/produces-fixture.js
test/handlers/test-me.js
test/handlers/test-post-login-handler.js
test/handlers/test-post-registration-handler.js
test/helpers/test-get-required-registration-fields.js
test/helpers/test-get-user.js
test/helpers/test-prep-account-data.js
test/helpers/test-sanitize-form-data.js
test/helpers/test-validate-account.js

This commit brings the config.yaml up-to-date with the latest copy from the framework spec.
As such, several of the form parsing files needed modifications in order to find the field and filed order definitions in their new locations, under the `form` key.
With this commit I am also removing the `website` and `api` options, as intended for the 3.0 release.  The features that were enabled by these options are now enabled by default, so these options are no longer necessary.

Update to latest config, remove website and api options

---

docs/upgrading.rst
lib/controllers/register.js
lib/helpers/index.js
lib/helpers/login-responder.js
lib/helpers/stripped-account-response.js
test/controllers/test-login.js
test/controllers/test-register.js

* Don’t expose linked resources
* Wrap account data in the `account` object key.

Registration login updates

---

docs/upgrading.rst
lib/stormpath.js

* Don’t use getUser for un-authenticated routes, that is now opt-in
* Hold requests until stormpath is ready, so that the developer no longer needs to wait on the `stormpath.ready` event.
Closes #285

getUser changes, stormpath.ready event changes

---

lib/controllers/register.js
test/controllers/test-register.js

If the user supplies the value, but the field is optional, we should not override with UNKNOWN
Closes #329

Fix UNKNOWN override when name field optional

---

lib/config.yml
lib/helpers/create-session.js
test/controllers/test-login.js

During the yaml upgrades, we forgot to default the cookie path to / if not specified.  This is required because if we omit the path, the cookies will be set on the /callback URI when social login happens, and those cookies are then trapped on that URL and can’t be used on the rest of the site.
I’ve added a test case in the login controller test, to assert that we set the cookies with the default path of /
I’ve also refactored that test file to create two express apps fixtures in the begin block, which is must faster than creating one at every block.  This is a test change that I’ve been implementing in most of my PRs.
I’ve added some clarifying comments to the yaml file, about cookies. Ideally we would have some actual IT tests to assert social callbacks, but this new test will work for …

Fix cookies for social login

---

lib/config.yml
lib/controllers/index.js
lib/controllers/linkedin-login.js
lib/oauth/linkedin.js

This PR fixes a couple of issues that made LinkedIn login not work.
* 9bdf86f – Renamed `linkedInLogin` controller to `linkedinLogin`, otherwise it would not be found at all
* 7bf9c2a – Changed default LinkedIn scopes to be space delimited instead of comma delimited
Fixes #305.
1. Checkout this branch
2. Checkout [express-stormpath-sample-project](https://github.com/stormpath/express-stormpath-sample-project)
2. Configure a Directory with LinkedIn
3. Run the example (linked to `express-stormpath` ofc).
4. Verify that LinkedIn login works without errors

Fix LinkedIn login

---

lib/stormpath.js

Quick change to get these cached warmed, so that you're not waiting on them when you load your Angular application for the first time.  Not a huge fan of the anon callbacks, can refactor later if desireed.

pre-warm view model cache for faster SPA applications

---

lib/controllers/logout.js

Invalidates the account cache when the `/logout` endpoint is called.
This depends on https://github.com/stormpath/stormpath-sdk-node/pull/407 in order to function. So the Node SDK need to cut a new release with that PR before we can release this.
Run the steps of [this PR](https://github.com/stormpath/stormpath-sdk-node/pull/407). It will use this branch and verify the behaviour.
Fixes #278.

Fix: Invalidate cache at logout

---

lib/controllers/facebook-login.js
lib/controllers/github-login.js
lib/oauth/common.js

Add support for exchanging a Facebook authorization code for an access token.
1. Log into the Stormpath Console and map a Facebook directory to your application.
2. Checkout [the Angular JS example project](https://github.com/stormpath/stormpath-sdk-angularjs/tree/master/example/dashboard-app). Run it and verify that you can login with Facebook. This tests authentication with an access token.
3. Go to [this React SDK PR](https://github.com/stormpath/stormpath-sdk-react/pull/46). Do steps 1-8 and step 10 (but only for the Facebook provider). This tests authentication with an authorization code.

Add Facebook authorization code support

---

docs/configuration.rst
docs/registration.rst
docs/setup.rst

Previously, the steps required to get started with this module were split between the “Setup” page and the “Configuration” page.
This PR fixes that strangeness.  The “Setup” page is now quickstart-like, and the “Configuration” page has more in-depth information about how to configure the library, and what the defaults are.

Updates to the Setup and Configuration documentation

---

docs/login.rst
docs/registration.rst
lib/controllers/login.js
lib/controllers/register.js
lib/helpers/index.js
lib/helpers/write-form-error.js
package.json
test/handlers/test-pre-login-handler.js
test/handlers/test-pre-registration-handler.js

Adds support for the `preRegistrationHandler` and `preLoginHandler`.
2. Link it (`$ npm link`).
3. Create a new test application using [this gist](https://gist.github.com/typerandom/94ed68b0ff541bf84597).
4. Link to our branch (`$ npm link express-stormpath`).
5. Start the application.
6. Navigate to `/register`.
7. Try and register with the email `test@test.com`.
8. Verify that you receive the error message `You're not allowed to register as 'test@test.com'.`.
9. Change the email to your own and set a really short password.
10. Verify that you receive an error stating that your password is too short.
11. Register for a new account.
12. Verify that the registration process works as expected.
13. Logout from your account.
14. Navigate to `/login`.
15. Try to login …

Add support for preRegistrationHandler and preLoginHandler

---

docs/logout.rst
lib/controllers/logout.js
package.json
test/controllers/test-logout.js
test/handlers/test-post-logout-handler.js
test/helpers.js

Adds support for the `postLogoutHandler`.
This depends on [stormpath-sdk-node/release-0.18.0](https://github.com/stormpath/stormpath-sdk-node/pull/411)
2. Link it (`$ npm link`).
3. Create a new test application using [this gist](https://gist.github.com/typerandom/f98d5867f9b7123c4873).
4. Link to our branch (`$ npm link express-stormpath`).
5. Start the application.
6. Navigate to `/login`.
7. Login as an existing user.
8. Navigate to `/logout`.
9. Click the logout button.
10. Check the console and verify that `'User logged out (account object)` is present.
Fixes #218.

Add support for postLogoutHandler

---

lib/middleware/api-authentication-required.js
test/middlewares/test-api-authentication-required.js

Fixes #261 
It's now possible to use `stormpath.apiAuthenticationRequired` with the `stormpath` validation strategy.
To verify, create a simple application that uses the `apiAuthenticationRequired` middleware, with the `stormpath` validation option:
```javascript
var express = require('express');
var stormpath = require('express-stormpath');
var app = express();
app.use(stormpath.init(app, {
web: {
oauth2: {
password: {
validationStrategy: 'stormpath'
}
}
}
}));
app.get('/', stormpath.apiAuthenticationRequired, function (req, res) {
res.json({'hello': req.user.fullName});
});
app.listen(3000);
```
Then get an access token:
> curl -X POST -d grant_type=password -d username=XXX -d password=YYY http://localhost:3000/oauth/token
And use that access token to authenticate with the server:
> …

Use JwtAuthenticator for Bearer authentication requests

---

lib/controllers/change-password.js
test/controllers/test-reset-password.js

In the failure case, we need to render a JSON error message (not redirect to the login page).  Fixes #385 
To verify:
* Use this branch with the [Stormpath Angular + Express Fullstack Sample Project](https://github.com/stormpath/express-stormpath-angular-sample-project)
* Visit http://localhost:3000/change?sptoken=x
With the fix, you should see the error message: "This password reset link is not valid. You may request another link by clicking here." (Expected behaviour)
Without the fix, you should see the change password (problem behaviour).
I've added a new test for HTML vs JSON on this endpoint, and refeactored this test file to use a single default express application (where possible)..

Fixing JSON response for verifying password reset tokens

---

docs/configuration.rst
lib/stormpath.js
test/helpers.js
test/test-stormpath.js

Fixes #383 
Custom loggers were not being used, and only one log level string can be used.
Cleaning up stormpath.init() tests while I’m at it.

Logger fixes

---

lib/middleware/api-authentication-required.js
package.json

3.1.0 did not carry over the local validation option to `authenticateApiRequest`, this fixes that problem.

Fix broken local validaion

---

lib/controllers/change-password.js
test/controllers/test-reset-password.js

Another fix for #385.  In #388 we fixed the invalid token case but broke the valid token case in ef8822a13ffb7965b2e308cc37bc3984db766967.
I've added more tests to ensure that we don't break this API in the future, we also need to look at the email verification API to ensure that it is working correctly for JSON and that it has tests.

more change-password fixes

---

lib/views/login.jade

There's a typo in the message once the password has been reset: `Successfuly` => `Successfully`
Run the [express-stormpath-sample-project](https://github.com/stormpath/express-stormpath-sample-project) and reset your password. Once the password is reset, verify that you see this message:
> Password Reset Successfully

Typo: Successfuly => Successfully

---

lib/helpers/write-json-error.js
lib/middleware/groups-required.js
test/middlewares/test-groups-required.js

Fixes the `groupsRequired` middleware so that it responds correctly to the Accept header.
1. Create a new application using [this gist](https://gist.githubusercontent.com/typerandom/7a85bdaf7792e067c230faea6a56d301/raw/35944ec0d05cd26221f0d475d36fcd83e195fb69/stormpath-express-groups-required-example.js).
2. Without being authenticated, send a `GET` request to `/admin` with a `Accept: text/html` header. This should respond with a location header, redirecting you to the login.
3. Without being authenticated, send a `GET` request to `/admin` with a `Accept: application/json` header. This should respond with a JSON response body and a `401 Unauthorized` status code.
4. Being authenticated, send a `GET` request to `/admin` with a `Accept: text/html` header. This should respond with a location …

Fix groupsRequired middleware so that it handles Accept header

---

docs/templates.rst

Fixed a typo in doc (Email Verifiation Page --> Email Verification Page)

---

lib/helpers/render.js

Fixes so that the render method calls res.render() with the original view path.
(will be added soon)
Fixes #404

Fix issue with res.render() in render util not being called with original view path

---

lib/helpers/exchange-stormpath-token.js

This will make it easier to debug issues with social login flows, where things can go wrong at this step, specifically if the clock of the local sever is not in sync with ntp, and we get a token expired error because of it.

Surface token exchange errors via info() logger

---

lib/helpers/login-with-oauth-provider.js

Fixes so that login/registration pre/post handlers are triggered when authenticating with an OAuth provider.
Create a sample application that defines pre and post login, registration handlers.
When using the access token flow for a social provider, and authenticating for the first time (and account will be created in stormpath), the following handlers should be run:
* preRegistrationHandler
* postRegistrationHandler
* preLoginHandler
* postLoginHandler
Then when authenticating for a second time (the account already exists in stormpath), the following handlers should run:
* preLoginHandler
* postLoginHandler
Fixes #451 
Fixes #452

Fix login/registration handlers for oauth provider login

---

lib/controllers/facebook-login.js
lib/controllers/github-login.js
lib/helpers/get-host.js
lib/helpers/index.js
lib/oauth/linkedin.js
lib/stormpath.js

Due to this issue: https://github.com/expressjs/express/issues/2179
This fixes social login, when running behind a reverse proxy, where the redirect URL is dependent on proper hostname resolution.

Implement better dynamic host resolution

---

docs/login.rst

Fixes the login docs so that `login` is used instead of `username`.
Review the doc changes.
Fixes #486

Login docs should use `login` instead of `username`

---

lib/controllers/facebook-login.js
lib/controllers/github-login.js
lib/controllers/google-login.js
lib/controllers/linkedin-login.js
lib/helpers/set-temp-cookie.js
lib/oauth/common.js
lib/stormpath.js
test/helpers/test-get-user.js

Fixes so that login with social providers support the `?next` query string parameter.
2. Run `$ npm link`.
3. Use [this](https://gist.github.com/typerandom/0887f0085c77ccadd2f04859ce876385) example application.
4. Link it to the branch `$ npm link express-stormpath`.
5. Run the application.
6. Navigate to `http://localhost:3000/hello`.
7. Verify that you are redirected to `http://localhost:3000/login?next=%2Fhello`.
8. Login with either Facebook, Google, GitHub or LinkedIn.
9. Verify that you are redirected back to `http://localhost:3000/hello`.
The API-key secret is used to sign the `oauthStateRedirectUri` cookie. Any objections to this?
Fixes #482

Fix: Social login not respecting ?next

---

docs/_templates/layout.html

We added the GTM script to the upstream sphinx theme:
https://github.com/stormpath/stormpath-sphinx-theme/pull/3
As such, removing the old scripts in the local layout override.  Optimizely does need to stay in the fodder.

Updating docs to use google tag manager

---

docs/setup.rst

Correct `stormpath.init()` docs so that it states that it blocks **all requests**.
Look at the doc changes.
Fixes #491

Correct stormpath.init() docs

---

lib/views/login.jade

Fixes so that the login form view reflects the `web.login.form.fields` configuration.
Using the application below, verify that the `web.login.form.fields` config set in the application reflects the [http://localhost:3000/login](http://localhost:3000/login) view.
``` javascript
var express = require('express');
var stormpath = require('express-stormpath');
var app = express();
app.use(stormpath.init(app, {
debug: 'info',
web: {
login: {
form: {
fields: {
login: {
label: 'LOGIN LABEL',
placeholder: 'THIS IS THE LOGIN PLACEHOLDER'
},
password: {
label: 'PASSWORD LABEL',
placeholder: 'THIS IS THE PASSWORD PLACEHOLDER'
}
}
}
}
}
}));
app.on('error', function (err) {
console.error(err);
});
app.listen(3000, function () {
console.log('Listening on http://localhost:3000/!');
});
```
Fixes #478

Fix login form so that it reflects config

---

lib/helpers/login-with-oauth-provider.js

Fixes the OAuth login case where the `postRegistrationHandler` is set without `preLoginHandler`.
1. Set a `postRegistrationHandler` in config.
2. Start your express test application and login in with a OAuth provider.
3. Verify that you see the error `TypeError: preHandler is not a function` in console.
4. Checkout this branch.
5. Start your express test application and login in with a OAuth provider.
6. Verify that you are able to login without any error being shown in console.
Fixes #513

Fix OAuth login case when postRegistrationHandler is set but preLoginHandler is missing

---

docs/login.rst
lib/controllers/get-token.js

Add so that the OAuth2 endpoint (/oauth/token) supports the preLoginHandler and postLoginHandler when authenticating using password grant.
Use the code below:
``` javascript
var express = require('express');
var stormpath = require('express-stormpath');
var app = express();
app.use(stormpath.init(app, {
preLoginHandler: function (options, req, res, next) {
console.log('Got login request', options);
next();
},
postLoginHandler: function (account, req, res, next) {
console.log('Logged in as ', account.href);
next();
}
}));
app.listen(3000, function () {
console.log('Listening on http://localhost:3000/!');
});
```
And then call the endpoint `http://localhost:3000/oauth/token` with the form body `grant_type=password&username=(valid username)&password=(valid password)`.
Then verify that the …

Add OAuth2 password grant preLoginHandler and postLoginHandler support

---

lib/controllers/id-site-redirect.js

Fixes the host used in the id site redirect callback.
Deploy this branch behind a proxy (e.g. on Heroku). Then with ID site enabled, try initiating a logout request and verify that you are redirected back properly.
Fixes #534

Fix host used in id site redirect callback

---

docs/changelog.rst
docs/upgrading.rst
package.json

Release 3.1.7

---

docs/configuration.rst

Added missing comma under 'Disabling Features'. 
https://github.com/stormpath/express-stormpath/issues/568

Documentation: Fixed typo

---

package.json

- The dependency stormpath-config handles the configuration
helpers that are used by the SDK.
- This update is necessary as there is an update within the
EnrichIntegrationFromRemoteConfigStrategy file which
sets the client on the outerScope object.  Without this
the calls to getGroups wil yield undefined.  This was
resolved with this commit:
https://github.com/stormpath/stormpath-node-config/commit/49461660d2614cbf130cb788f458fd5e0cd1c996
closes #579 #580

Update stormpath config dependency

---

docs/authentication.rst
lib/middleware/authentication-required.js
lib/middleware/get-user.js
lib/stormpath.js
package.json
test/middlewares/test-get-user.js

**Work In Progress**
Updates this library to use the new `StormpathAccessTokenAuthenticator`, in a backwards-compatible way, so that we can release a patch release that will allow this library to properly authenticate access tokens that are issued by the Client API.
Depends on the `access-token-authenticator` branch in the Node SDK, as seen in this PR:
https://github.com/stormpath/stormpath-sdk-node/pull/597
Todo:

Use new access token authenticator (Client API Support)

---

docs/user_data.rst

In the example there is a missing closing parenthesis.

Add missing parenthesis to user data example

---

docs/login.rst

Added a little more info about the /idSiteResult endpoint to explain what it's used for and how it can be used in the SAML/Social login workflows. I think this will work for now until the stormpath callback endpoint is implemented and documented.

#586: /idSiteResult endpoint

---

lib/helpers/validate-account.js
test/helpers/test-validate-account.js

Fixes several issues with the account field validation helper:
1. Error generation used `field.label || field.label` instead of `field.label || field.name`
2. It considered all falsy values to be missing when `required: true`, when `false` or `null` can be legitimate values.
3. It did not validate required custom fields directly. It now looks into `customData`
Fixes https://github.com/stormpath/stormpath-express-react-example/issues/29

Fix field validation

---

docs/changelog.rst
lib/controllers/register.js
lib/controllers/verify-email.js
lib/stormpath.js
okta-todo.md
package.json
test/controllers/test-email-verification.js
test/controllers/test-register.js
util/okta-test-data.js

Please see docs/changelog.rst for a summary of changes.  This work depends on the in-progress `okta` branch in the Stormpath Node SDK.  
This PR will be immediately merged into the 4.0.0 branch.  Please continue to reference #609 for details about the migration.

Rework registration to work with Okta
