stormpath/express-stormpath

- lib/controllers.js
- lib/forms.js
- lib/settings.js
- lib/views/register.jade
> Added enableConfirmPassword for registration form.

- lib/authentication.js
> Retains query parameters upon login redirect

- package.json
> Adding uuid as a dependency.

- .travis.yml
- docs/changelog.rst
- docs/upgrading.rst
- package.json
> Cutting new Release

- docs/authentication.rst
> Fixed spelling error in authentication.rst

- lib/views/register.jade
Small issue that causing the register form submit empty POST data.
> fix fields name in register form

- README.md
> Correct the branch name in the readme

- LICENSE
- README.md
This PR includes:
* a new README.md file with a quick-start guide
* a LICENSE file for Apache v2.0
Please try out the guide and verify that everything stated is correct and produces a valid result.
@rdegges @typerandom @robertjd  please review.
> New README.md file with a quick-start guide

- lib/views/google_login_form.jade
#118 This will fix issues with var next giving an error, especially since this variable is never used to begin with.
> fixed google plus integration

- docs/changelog.rst
- docs/contributors.rst
- lib/controllers/google-login.js
Opening PR from this repo so that travis can run tests
Closes #137
> Fixes #136 - Google login does not create session

- docs/changelog.rst
- lib/controllers/logout.js
Closes #140 #138 - Thanks @ldhertert
> Logout idsite config

- docs/authentication.rst
- docs/changelog.rst
- docs/configuration.rst
- docs/introduction.rst
- docs/login.rst
- docs/password_reset.rst
- docs/registration.rst
- docs/setup.rst
- docs/social_login.rst
- docs/templates.rst
- docs/user_data.rst
Read through all the docs and corrected some typos for you guys :)
> Fixed a ton of typos

- docs/changelog.rst
Was informed that deprecation is actually correct! woops!
> Refixed a typo!

- package.json
> Depdency maintenance

- docs/changelog.rst
- docs/contributors.rst
- package.json
> Release 2.1.0

- docs/changelog.rst
- docs/contributors.rst
- docs/upgrading.rst
- package.json
> Release 2.2.0

- lib/controllers/login.js
- lib/views/login.jade
- package.json
Fixes so that the social providers UI box is only shown if there are social providers present and enabled.
Fixes #182.
> Fix: Social providers UI box begin shown when no providers are present

- lib/controllers/logout.js
- lib/helpers/index.js
- lib/helpers/revoke-token.js
- lib/middleware/delete-cookies.js
- lib/middleware/index.js
- lib/middleware/revoke-tokens.js
- package.json
- test/controllers/test-logout.js
Revoke refresh and access tokens when logging out.
Depends on https://github.com/stormpath/stormpath-sdk-node/pull/273 to be merged.
Closes #127.
> Feature: Revoke refresh/access token on logout

- docs/changelog.rst
- docs/registration.rst
- docs/upgrading.rst
- lib/config.yml
- lib/controllers/register.js
- lib/helpers/get-form-model.js
- lib/helpers/get-required-registration-fields.js
- lib/helpers/index.js
- lib/helpers/prep-account-data.js
- lib/helpers/sanitize-form-data.js
- lib/helpers/validate-account.js
- lib/views/login.jade
- lib/views/register.jade
- test/controllers/test-register.js
- test/handlers/test-post-registration-handler.js
- test/helpers/test-get-required-registration-fields.js
- test/helpers/test-validate-account.js
Complies with the [framework spec PR](https://github.com/stormpath/stormpath-framework-spec/pull/15) by removing certain registration fields from the config file and patching places where these fields were used.
Closes #183
> Feature: Comply with framework registration spec

- lib/stormpath.js
- test/controllers/test-email-verification.js
- test/controllers/test-forgot-password.js
- test/controllers/test-login.js
- test/controllers/test-register.js
- test/controllers/test-reset-password.js
- test/fixtures/spa-root-fixture.js
We were looking at the wrong option, and weren’t binding in all cases where we need to.
> Fixing the spaRoot option

- docs/changelog.rst
- package.json
See changelog and upgrade guide
> Release 2.3.0

- docs/upgrading.rst
Adding more notes in the 1.x -> 2.x section
> amend changelog

- docs/registration.rst
- lib/config.yml
- lib/views/register.jade
Right now we are using the placeholder value for the label value, which is silly
> Adding field label property for fields

- lib/controllers/facebook-login.js
- lib/controllers/google-login.js
> Support post login and registration handlers for social provider callbacks

- docs/authentication.rst
- docs/changelog.rst
- docs/contributors.rst
- docs/login.rst
- docs/registration.rst
- docs/upgrading.rst
- package.json
> Release 2.3.1

- docs/changelog.rst
- docs/upgrading.rst
- package.json
Small fix for Facebook callback.  See changelog.
> Release 2.3.2

- docs/changelog.rst
- docs/contributors.rst
- docs/upgrading.rst
- package.json
> Release 2.3.3

- docs/contributors.rst
- lib/controllers/logout.js
- test/controllers/test-logout.js
Closes #234 - Thanks @benjamincaldwell
> Adding ?next param for logout route

- docs/changelog.rst
- docs/upgrading.rst
- package.json
> Release 2.3.4

- lib/client.js
Enables the ability to set web features while still having the website option turned on.
Fixes #250.
> Fix: Ability to disable web features

- lib/controllers/register.js
Pass through the error from the underlying SDK
> Fixing JSON error responses in registration controller

- lib/controllers/id-site-verify.js
Handles the ID site `registered` result status.
Fixes #244.
> Fix: Handle id site registered status

- docs/configuration.rst
Adding useful information, and a slightly more clear wording.
> Updating configuration documentation.

- docs/changelog.rst
- package.json
> Release 2.3.7

- package.json
> stormpath@0.17.1

- docs/changelog.rst
- docs/upgrading.rst
- package.json
> Release 2.4.0

- lib/controllers/logout.js
Implements the produces option for /logout.
2. Clone [express-stormpath-sample-project](https://github.com/stormpath/express-stormpath-sample-project).
3. Use `npm link` and `npm link express-stormpath` to link the library to the example project.
4. Start the server.
5. Navigate to `/login` and login as a user.
6. Navigate to `/logout`.
7. Verify that you're logged out.
8. Use either the Angular or React SDK.
9. Validate that you can logout (with a `application/json` request).
Fixes #341.
> Add produces option for /logout

- docs/upgrading.rst
- lib/config.yml
- lib/controllers/current-user.js
- lib/controllers/facebook-login.js
- lib/controllers/github-login.js
- lib/controllers/google-login.js
- lib/controllers/id-site-verify.js
- lib/controllers/index.js
- lib/controllers/register.js
- lib/helpers/expand-account.js
- lib/helpers/get-user.js
- lib/helpers/login-responder.js
- lib/middleware/api-authentication-required.js
- lib/stormpath.js
- test/handlers/test-me.js
* Fire up the [express-stormpath-sample-project](https://github.com/stormpath/express-stormpath-sample-project)
* Link to this branch for express-stormpath dependency
* Assert the following:
* /me route does not expand linked resources on the account object, unless specified by `stormpath.web.me.expand.[resource]`
* /me route will respond with no-cache headers, see the diff for specific headers that are now being sent.
Closes #348.
> Current user updates

- docs/upgrading.rst
- lib/controllers/current-user.js
- lib/stormpath.js
- test/handlers/test-me.js
This PR just fixes some typos and whitespace adjustments while I was skimming through a couple of the merged PRs :)
@typerandom please have a look and then merge.
> Whitespace and typo fixes

- lib/controllers/register.js
- lib/helpers/prep-account-data.js
- lib/helpers/sanitize-form-data.js
- lib/helpers/validate-account.js
- test/handlers/test-post-registration-handler.js
- test/helpers/test-get-required-registration-fields.js
- test/helpers/test-prep-account-data.js
- test/helpers/test-sanitize-form-data.js
- test/helpers/test-validate-account.js
Fixes the registration form confirmation password (`confirmPassword`) field.
2. Link it (`$ npm link`).
3. Create a new test application using [this gist](https://gist.github.com/typerandom/ea3e9bb7797075bfded6).
4. Link to our branch (`$ npm link express-stormpath`).
5. Start the application.
6. Navigate to `/register`.
7. Verify that the the `Confirm Password` works as expected.
Fixes #257.
> Fix: Registration form confirm password field

- docs/configuration.rst
- docs/user_data.rst
> Document the current user route

- docs/changelog.rst
- docs/upgrading.rst
- package.json
See changelog and upgrade guide.
> Release 3.1.0

- docs/changelog.rst
- docs/upgrading.rst
- package.json
See Changelog and Upgrade Guide
> Release 3.1.1

- docs/changelog.rst
- docs/upgrading.rst
- package.json
See Changelog and Upgrade Guide.
> Release 3.1.2

- docs/contributors.rst
- lib/helpers/get-user.js
> Fix access refresh token names

- lib/helpers/get-user.js
This should fix: https://github.com/stormpath/express-stormpath/issues/411
> Use configured names for access token and refresh token when getting user

- docs/contributors.rst
- lib/middleware/delete-cookies.js
- test/controllers/test-logout.js
Re-opening from source repo so that tests can run.  Closes #443 #155
> Fix undeletable cookie

- README.md
Adding this badge to express-stormpath. I will be in the channel to support customers. 
[![Slack Status](https://talkstormpath.shipit.xyz/badge.svg)](https://talkstormpath.shipit.xyz)
> Adding slack badge

- docs/registration.rst
> Fix registration docs RE name field

- package.json
> stormpath@0.18.3

- .travis.yml
- docs/changelog.rst
- docs/upgrading.rst
- package.json
> Release 3.1.3

- docs/changelog.rst
- docs/upgrading.rst
- package.json
> Release 3.1.5

- lib/controllers/facebook-login.js
- lib/controllers/github-login.js
- lib/controllers/google-login.js
- lib/controllers/linkedin-login.js
- lib/controllers/logout.js
- lib/helpers/index.js
- lib/helpers/set-temp-cookie.js
- lib/middleware/get-user.js
- lib/middleware/index.js
- lib/oauth/common.js
- lib/stormpath.js
- test/helpers/test-get-user.js
- test/middlewares/test-get-user.js
This does exactly what the title says it does. All tests pass locally.
> Moving getUser into middleware folder for better organization.

- docs/_templates/layout.html
This PR updates all of the docs theme stuff to include all the latest and greatest things, including the tracking codez.
> Updated theme

- .travis.yml
We've got a simpler build system in place now-a-days, so I'm removing the unnecessary deployment code from this project.
> Removing unnecessary build steps.

- package.json
To fix issue with social login scope being overwritten with remote config
> Upgrade stormpath-config @ 0.0.26

- docs/changelog.rst
- docs/upgrading.rst
- package.json
> Release 3.1.6

- docs/changelog.rst
- docs/upgrading.rst
- package.json
> Release 3.1.8

- docs/changelog.rst
- docs/upgrading.rst
- package.json
> Release 3.1.9
